name: Update TradingView Widget

on:
  workflow_dispatch:
    inputs:
      html_content:
        description: "HTML content for TradingView widget"
        required: true

jobs:
  update_widget:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update TradingView HTML
        run: |
          echo "${{ github.event.inputs.html_content }}" > chart.html
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add chart.html
          git commit -m "Update TradingView widget"
          git push
