name: Triggered Workflow with Parameters

on:
  workflow_dispatch:
    inputs:
      custom_param:
        description: "Custom parameter"
        required: true
        default: "default_value"

jobs:
  run_task:
    runs-on: ubuntu-latest

    steps:
      - name: Print input parameter
        run: echo "Workflow triggered successfully!"
